### ISSUE TITLE
Create artisan command to copy SoccerAPIClient.php

### ISSUE THREAD

**Issue by ianmustafa** [sebastiaanspeck/matchy#54]
Instead of copying `SoccerAPIClient.php` manually to the `vendor` folder, I'm proposing an artisan command that can be called on step 7 of the installation. I can work for the PR if it's OK

**Comment by sebastiaanspeck** [comment]
That’s an option or create a custom SoccerAPI that extends the SoccerAPIClient.php and TopScorer.php. I don’t know what works best

**Comment by nickescobedo** [comment]
Copying to a vendor folder is rarely a good idea. Reason being every time the package in vendor is updated the files copied to vendor can be written over. Which means the user would have to know to copy the files each time. Composer was not built for that. I personally treat the vendor folder as disposable meaning if I wanted to at any time I can delete the folder and `composer install` and it would be exactly the same.

I can handle this for you @sebastiaanspeck if you'd like. Let me know.

**Comment by sebastiaanspeck** [comment]
Right now, the changes I made are added to the package. I will run tests tomorrow and if they work, this issue can be closed

**Comment by nickescobedo** [comment]
Are the changes pushed?

**Comment by sebastiaanspeck** [comment]
Yes

**Comment by nickescobedo** [comment]
So then no need to copy any files because your changes got merged in with that repo on dev-master?

**Comment by sebastiaanspeck** [comment]
Yes!

**Comment by sebastiaanspeck** [comment]
> Copying to a vendor folder is rarely a good idea. Reason being every time the package in vendor is updated the files copied to vendor can be written over. Which means the user would have to know to copy the files each time. Composer was not built for that. I personally treat the vendor folder as disposable meaning if I wanted to at any time I can delete the folder and `composer install` and it would be exactly the same.
> 
> I can handle this for you @sebastiaanspeck if you'd like. Let me know.

I have this problem again... How can I fix it now? Don't know if the package-owner is willing to change the package again...

**Comment by sebastiaanspeck** [comment]
Fixed by creating a fork and including the fork in composer.json

**Comment by nickescobedo** [comment]
@sebastiaanspeck Is it possible for you to extend the classes you need to make changes to and use those instead of having to maintain a fork? Would probably be easier on you in the long run.

**Comment by sebastiaanspeck** [comment]
Hmm.. Could be possible in the future, but I made various changes so this is the best solution right now
