### ISSUE TITLE
No such method exists: deviceType

### ISSUE THREAD

**Issue by Suwadith** [sebastiaanspeck/matchy#85]
As soon as I browse the [URL](http://localhost:8000/), this shows up. And nothing seems to be working :(

![image](https://user-images.githubusercontent.com/20539850/58821641-230d6a00-8653-11e9-87bc-a9f423fa6de8.png)

**Comment by sebastiaanspeck** [comment]
Please see this [PR](https://github.com/jenssegers/agent/pull/141)

**Comment by lakuapik** [comment]
Same here, i see the PR not merged yet.

**Comment by sebastiaanspeck** [comment]
Fixed with this [commit](https://github.com/sebastiaanspeck/matchy/commit/b8d850f168ff92d83e8dcd557d100c65f9c4a36f)
